import { registerFileHandlers } from './file';
import { registerProjectHandlers } from './project';
import { registerSessionHandlers } from './session';
import { registerExportHandlers } from './export';
import { registerAIHandlers } from './ai';
import { registerWikiHandlers } from './wiki';
import { registerFanlibHandlers } from './fanlib';
import { registerDesignHandlers } from './design';
import { registerPipelineHandlers } from './pipeline';
import { registerStoryboardHandlers } from './storyboard';
import { registerTemplateHandlers } from './template';
import { registerDialogHandlers } from './dialog';
import { registerWorkspaceHandlers } from './workspace';
import { registerImageHandlers } from './image';
import { registerShellHandlers } from './shell';
import { registerTimelineHandlers } from './timeline';
import { registerArcHandlers } from './arc';
import { registerPromptLogHandlers } from './prompt-log';
import { registerAIQueueHandlers } from '../services/ai-queue.service';

export function registerAllHandlers(): void {
  registerAIQueueHandlers();
  registerFileHandlers();
  registerProjectHandlers();
  registerSessionHandlers();
  registerExportHandlers();
  registerAIHandlers();
  registerWikiHandlers();
  registerFanlibHandlers();
  registerDesignHandlers();
  registerPipelineHandlers();
  registerStoryboardHandlers();
  registerTemplateHandlers();
  registerDialogHandlers();
  registerWorkspaceHandlers();
  registerImageHandlers();
  registerShellHandlers();
  registerTimelineHandlers();
  registerArcHandlers();
  registerPromptLogHandlers();
}
